function define_jugpet_data()
    jugpet = T {
        ["Homunculus"] = "Mandragora",
        ["HareFamiliar"] = "Rabbit",
        ["KeenearedSteffi"] = "Rabbit",
        ["CrabFamiliar"] = "Crab",
        ["CourierCarrie"] = "Crab",
        ["SheepFamiliar"] = "Sheep",
        ["LullabyMelodia"] = "Sheep",
        ["SlipperySilas"] = "Frog",
        ["FlytrapFamiliar"] = "Flytrap",
        ["VoraciousAudrey"] = "Flytrap",
        ["FlowerpotBill"] = "Mandragora",
        ["FlowerpotBen"] = "Mandragora",
        ["TigerFamiliar"] = "Tiger",
        ["SaberSiravarde"] = "Tiger",
        ["MayflyFamiliar"] = "Fly",
        ["ShellbusterOrob"] = "Fly",
        ["LizardFamiliar"] = "Lizard",
        ["ColdbloodComo"] = "Lizard",
        ["EftFamiliar"] = "Eft",
        ["AmbusherAllie"] = "Eft",
        ["FungaurFamiliar"] = "Fungaur",
        ["AntlionFamiliar"] = "Antlion",
        ["ChopsueyChucky"] = "Antlion",
        ["BeetleFamiliar"] = "Beetle",
        ["PanzerGalahad"] = "Beetle",
        ["MiteFamiliar"] = "Diremite",
        ["LifedrinkerLars"] = "Diremite",
        ["TurbidToloi"] = "Pugil",
        ["AmigoSabotender"] = "Sabotender",
        ["DapperMac"] = "Apkallu",
        ["CraftyClyvonne"] = "Coeurl",
        ["NurseryNazuna"] = "Sheep",
        ["LuckyLulush"] = "Rabbit",
        ["FlowerpotMerle"] = "Mandragora",
        ["DipperYuly"] = "Ladybug",
        ["DiscreetLouise"] = "Fungaur",
        ["FatsoFargann"] = "Leech",
        ["PrestoJulio"] = "Flytrap",
        ["AudaciousAnna"] = "Lizard",
        ["MailbusterCetas"] = "Fly",
        ["FaithfulFalcorr"] = "Hippogryph",
        ["SwiftSieghard"] = "Raptor",
        ["BloodclawShasra"] = "Coeurl",
        ["BugeyedBroncha"] = "Eft",
        ["GorefangHobs"] = "Tiger",
        ["GooeyGerard"] = "Slug",
        ["CrudeRaphie"] = "Adamantoise",
        ["AmiableRoche"] = "Pugil",
        ["SweetCaroline"] = "Mandragora",
        ["HeadbreakerKen"] = "Fly",
        ["AnklebiterJedd"] = "Diremite",
        ["CursedAnnabelle"] = "Antlion",
        ["BrainyWaluis"] = "Fungaur",
        ["SlimeFamiliar"] = "Slime",
        ["SultryPatrice"] = "Slime",
        ["GenerousArthur"] = "Slug",
        ["RedolentCandi"] = "Snapweed",
        ["AlluringHoney"] = "Snapweed",
        ["LynxFamiliar"] = "Coeurl",
        ["VivaciousGaston"] = "Coeurl",
        ["CaringKiyomaro"] = "Raaz",
        ["VivaciousVickie"] = "Raaz",
        ["SuspiciousAlice"] = "Eft",
        ["SurgingStorm"] = "Apkallu",
        ["SubmergedIyo"] = "Apkallu",
        ["WarlikePatrick"] = "Lizard",
        ["RhymingShizuna"] = "Sheep",
        ["BlackbeardRandy"] = "Tiger",
        ["ThreestarLynn"] = "Ladybug",
        ["HurlerPercival"] = "Beetle",
        ["AcuexFamiliar"] = "Acuex",
        ["FluffyBredo"] = "Acuex",
        ["WeevilFamiliar"] = "Ladybug",
        ["StalwartAngelina"] = "Ladybug",
        ["FleetReinhard"] = "Raptor",
        ["SharpwitHermes"] = "Mandragora",
        ["PorterCrabFamiliar"] = "Crab",
        ["JovialEdwin"] = "Crab",
        ["AttentiveIbuki"] = "Tulfaire",
        ["SwoopingZhviago"] = "Tulfaire",
        ["SunburstMalfik"] = "Crab",
        ["AgedAngus"] = "Crab",
        ["ScissorlegXerin"] = "Chapuli",
        ["BouncingBertha"] = "Chapuli",
        ["SpiderFamiliar"] = "Spider",
        ["GussyHachirobe"] = "Spider",
        ["ColibriFamiliar"] = "Colibri",
        ["ChoralLeera"] = "Colibri",
        ["DroopyDortwin"] = "Rabbit",
        ["PonderingPeter"] = "Rabbit",
        ["HeraldHenry"] = "Crab",
        ["HippogryphFamiliar"] = "Hippogryph",
        ["DaringRoland"] = "Hippogryph",
        ["MosquitoFamiliar"] = "Mosquito",
        ["Left-HandedYoko"] = "Mosquito",
        ["BraveHeroGlenn"] = "Frog",
        ["YellowBeetleFamiliar"] = "Beetle",
        ["EnergizedSefina"] = "Beetle",
    }

    monster_species = T {
        ["Rabbit"] = "Beast",
        ["Mandragora"] = "Plantoid",
        ["Crab"] = "Aquan",
        ["Sheep"] = "Beast",
        ["Frog"] = "Aquan",
        ["Flytrap"] = "Vermin",
        ["Tiger"] = "Beast",
        ["Eft"] = "Lizard",
        ["Fungaur"] = "Plantoid",
        ["Antlion"] = "Vermin",
        ["Beetle"] = "Vermin",
        ["Diremite"] = "Vermin",
        ["Pugil"] = "Aquan",
        ["Sabotender"] = "Plantoid",
        ["Apkallu"] = "Bird",
        ["Ladybug"] = "Vermin",
        ["Leech"] = "Amorph",
        ["Raptor"] = "Lizard",
        ["Hippogryph"] = "Bird",
        ["Coeurl"] = "Beast",
        ["Fly"] = "Insect",
        ["Adamantoise"] = "Aquan",
        ["Slug"] = "Amorph",
        ["Snapweed"] = "Plantoid",
        ["Raaz"] = "Beast",
        ["Acuex"] = "Amorph",
        ["Tulfaire"] = "Bird",
        ["Chapuli"] = "Vermin",
        ["Spider"] = "Vermin",
        ["Colibri"] = "Bird",
        ["Mosquito"] = "Vermin",
        ["Slime"] = "Aquan",
    }

    monster_family_killer = T {
        ["Beast"] = "Lizard",
        ["Lizard"] = "Vermin",
        ["Vermin"] = "Plantoid",
        ["Plantoid"] = "Beast",
        ["Aquan"] = "Amorph",
        ["Amorph"] = "Bird",
        ["Bird"] = "Aquan",

        ["Undead"] = "Arcana",
        ["Arcana"] = "Undead",
        ["Dragon"] = "Demon",
        ["Demon"] = "Dragon"
    }
end

function get_pet_killer_trait(pet_name)
    if pet_name and jugpet[pet_name] then
        return monster_family_killer[monster_species[jugpet[pet_name]]] .. ' Killer'
    end
end

define_jugpet_data()
