sets.exported={
    main={ name="Grioavolr", augments={'Mag. Acc.+16','STR+8','Magic burst dmg.+13%','Magic Damage +7',}},
    sub="Enki Strap",
    range="Dunna",
    head={ name="Merlinic Hood", augments={'Mag. Acc.+24 "Mag.Atk.Bns."+24','INT+3','Mag. Acc.+13','"Mag.Atk.Bns."+15',}},
    body="Shango Robe",
    hands={ name="Amalric Gages", augments={'INT+10','Mag. Acc.+15','"Mag.Atk.Bns."+15',}},
    legs={ name="Merlinic Shalwar", augments={'Mag. Acc.+12','"Store TP"+3','Accuracy+9 Attack+9','Mag. Acc.+19 "Mag.Atk.Bns."+19',}},
    feet="Mallquis Clogs +1",
    neck="Sanctity Necklace",
    waist="Eschan Stone",
    left_ear="Hermetic Earring",
    right_ear="Lugalbanda Earring",
    left_ring="Kishar Ring",
    right_ring="Stikini Ring",
    back={ name="Nantosuelta's Cape", augments={'INT+20','Mag. Acc+18 /Mag. Dmg.+18','Mag. Acc.+1',}},
}