sets.exported={
    main="Dojikiri Yasutsuna",
    sub="Utu Grip",
    range="Yoichinoyumi",
    ammo="Yoichi's Arrow",
    head="Ken. Jinpachi",
    body="Ken. Samue +1",
    hands="Ken. Tekko",
    legs="Ken. Hakama",
    feet="Ken. Sune-Ate",
    neck="Combatant's Torque",
    waist="Reiki Yotai",
    left_ear="Cessance Earring",
    right_ear="Telos Earring",
    left_ring="Cacoethic Ring",
    right_ring="Cacoethic Ring +1",
    back={ name="Smertrios's Mantle", augments={'AGI+20','Rng.Acc.+20 Rng.Atk.+20','Rng.Acc.+10','"Store TP"+10',}},
}