sets.exported={
    main="Oranyan",
    sub="Clerisy Strap +1",
    ammo="Impatiens",
    head={ name="Merlinic Hood", augments={'"Fast Cast"+6',}},
    body={ name="Merlinic Jubbah", augments={'"Mag.Atk.Bns."+16','"Fast Cast"+6','INT+4',}},
    hands={ name="Merlinic Dastanas", augments={'Mag. Acc.+2','"Fast Cast"+6','"Mag.Atk.Bns."+1',}},
    legs={ name="Psycloth Lappas", augments={'MP+80','Mag. Acc.+15','"Fast Cast"+7',}},
    feet="Regal Pumps +1",
    neck="Voltsurge Torque",
    waist="Witful Belt",
    left_ear="Loquac. Earring",
    right_ear="Enchntr. Earring +1",
    left_ring="Weather. Ring",
    right_ring="Kishar Ring",
    back="Perimede Cape",
}