sets.exported={
    main={ name="Brilliance", augments={'Shield skill +10','Divine magic skill +15','Enmity+7','DMG:+15',}},
    sub="Srivatsa",
    ammo="Ginsen",
    head="Flam. Zucchetto +2",
    body={ name="Valorous Mail", augments={'Accuracy+20 Attack+20','"Store TP"+7','Attack+9',}},
    hands="Sulev. Gauntlets +2",
    legs={ name="Valor. Hose", augments={'Accuracy+30','"Store TP"+8','CHR+7',}},
    feet="Flam. Gambieras +2",
    neck="Combatant's Torque",
    waist="Grunfeld Rope",
    left_ear="Cessance Earring",
    right_ear="Brutal Earring",
    left_ring="Regal Ring",
    right_ring="Flamma Ring",
    back={ name="Rudianos's Mantle", augments={'STR+20','Accuracy+20 Attack+20','STR+10','Weapon skill damage +10%',}},
}