sets.exported={
    main="Heishi Shorinken",
    sub={ name="Ochu", augments={'STR+10','DEX+10','Ninjutsu skill +10','DMG:+15',}},
    ammo="Seki Shuriken",
    head={ name="Herculean Helm", augments={'Damage taken-2%','DEX+5',}},
    body="Hiza. Haramaki +1",
    hands={ name="Herculean Gloves", augments={'Attack+4','"Triple Atk."+4','DEX+1','Accuracy+14',}},
    legs={ name="Samnuha Tights", augments={'STR+10','DEX+10','"Dbl.Atk."+3','"Triple Atk."+3',}},
    feet="Hachiya Kyahan",
    neck="Loricate Torque +1",
    waist="Flume Belt +1",
    left_ear="Odnowa Earring +1",
    right_ear="Genmei Earring",
    left_ring="Warp Ring",
    right_ring="Defending Ring",
    back="Solemnity Cape",
}