sets.exported={
    main="Heishi Shorinken",
    sub={ name="Ochu", augments={'STR+10','DEX+10','Ninjutsu skill +10','DMG:+15',}},
    ammo="Seki Shuriken",
    head="Ken. Jinpachi",
    body="Ken. Samue +1",
    hands="Ken. Tekko",
    legs="Ken. Hakama",
    feet="Ken. Sune-Ate",
    neck="Moonbeam Nodowa",
    waist="Reiki Yotai",
    left_ear="Telos Earring",
    right_ear="Suppanomimi",
    left_ring="Epona's Ring",
    right_ring="Hetairoi Ring",
    back={ name="Andartia's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','"Dbl.Atk."+10',}},
}