sets.exported={
    main="Freydis",
    sub="Adapa Shield",
    ammo="Staunch Tathlum",
    head="Pummeler's Mask +3",
    body={ name="Souveran Cuirass", augments={'HP+80','Enmity+7','Potency of "Cure" effect received +10%',}},
    hands="Pumm. Mufflers +3",
    legs="Sulev. Cuisses +2",
    feet={ name="Souveran Schuhs", augments={'HP+80','Enmity+7','Potency of "Cure" effect received +10%',}},
    neck="Loricate Torque +1",
    waist="Flume Belt +1",
    left_ear="Cryptic Earring",
    right_ear="Trux Earring",
    left_ring="Apeile Ring +1",
    right_ring="Apeile Ring",
    back="Philidor Mantle",
}