sets.exported={
    main={ name="Akademos", augments={'INT+15','"Mag.Atk.Bns."+15','Mag. Acc.+15',}},
    sub="Irenic Strap +1",
    ammo="Incantor Stone",
    head={ name="Vanya Hood", augments={'MP+50','"Fast Cast"+10','Haste+2%',}},
    body={ name="Amalric Doublet", augments={'MP+60','Mag. Acc.+15','"Mag.Atk.Bns."+15',}},
    hands={ name="Amalric Gages", augments={'MP+60','Mag. Acc.+15','"Mag.Atk.Bns."+15',}},
    legs={ name="Psycloth Lappas", augments={'MP+80','Mag. Acc.+15','"Fast Cast"+7',}},
    feet="Volte Boots",
    neck="Sanctity Necklace",
    waist="Luminary Sash",
    left_ear="Loquac. Earring",
    right_ear={ name="Moonshade Earring", augments={'MP+25','TP Bonus +250',}},
    left_ring="Mephitas's Ring +1",
    right_ring="Etana Ring",
    back="Pahtli Cape",
}