sets.exported={
    main="Hvergelmir",
    sub="Enki Strap",
    ammo="Pemphredo Tathlum",
    head={ name="Vanya Hood", augments={'MP+50','"Fast Cast"+10','Haste+2%',}},
    body={ name="Merlinic Jubbah", augments={'"Mag.Atk.Bns."+16','"Fast Cast"+6','INT+4',}},
    hands={ name="Merlinic Dastanas", augments={'Chance of successful block +1','Weapon skill damage +4%','"Refresh"+1','Accuracy+20 Attack+20',}},
    legs={ name="Psycloth Lappas", augments={'MP+80','Mag. Acc.+15','"Fast Cast"+7',}},
    feet="Regal Pumps +1",
    neck="Voltsurge Torque",
    waist="Witful Belt",
    left_ear="Loquac. Earring",
    right_ear="Enchntr. Earring +1",
    left_ring="Kishar Ring",
    right_ring="Weather. Ring",
    back="Perimede Cape",
}