sets.exported={
    main="Perun +1",
    sub="Nusku Shield",
    range="Yoichinoyumi",
    ammo="Yoichi's Arrow",
    head={ name="Herculean Helm", augments={'Rng.Acc.+28','Weapon skill damage +3%','DEX+11','Rng.Atk.+12',}},
    body="Meg. Cuirie +1",
    hands="Meg. Gloves +1",
    legs="Darraigner's Brais",
    feet="Thereoid Greaves",
    neck="Fotia Gorget",
    waist="Fotia Belt",
    left_ear={ name="Moonshade Earring", augments={'MP+25','TP Bonus +25',}},
    right_ear="Sherida Earring",
    left_ring="Regal Ring",
    right_ring="Dingir Ring",
    back={ name="Belenus's Cape", augments={'DEX+20','Rng.Acc.+20 Rng.Atk.+20','DEX+10','Crit.hit rate+10',}},
}