sets.exported={
    main="Trishula",
    sub="Utu Grip",
    ammo="Ginsen",
    head="Flam. Zucchetto +1",
    body={ name="Valorous Mail", augments={'Accuracy+22','"Store TP"+7',}},
    hands={ name="Valorous Mitts", augments={'Accuracy+13 Attack+13','CHR+5','Quadruple Attack +3','Mag. Acc.+19 "Mag.Atk.Bns."+19',}},
    legs="Sulev. Cuisses +2",
    feet={ name="Valorous Greaves", augments={'Accuracy+26','"Dbl.Atk."+4','DEX+8','Attack+3',}},
    neck="Shulmanu Collar",
    waist="Ioskeha Belt",
    left_ear="Cessance Earring",
    right_ear="Sherida Earring",
    left_ring="Niqmaddu Ring",
    right_ring="Petrov Ring",
    back={ name="Brigantia's Mantle", augments={'STR+20','Accuracy+20 Attack+20','STR+10','"Dbl.Atk."+10',}},
}