sets.exported={
    main="Chango",
    sub="Utu Grip",
    ammo="Staunch Tathlum",
    head="Pummeler's Mask +3",
    body="Pumm. Lorica +3",
    hands="Pumm. Mufflers +3",
    legs="Pumm. Cuisses +3",
    feet="Pumm. Calligae +3",
    neck="Warder's Charm +1",
    waist="Engraved Belt",
    left_ear="Eabani Earring",
    right_ear="Flashward Earring",
    left_ring="Purity Ring",
    right_ring="Vengeful Ring",
    back={ name="Cichol's Mantle", augments={'MND+20','Eva.+20 /Mag. Eva.+20','Mag. Evasion+10',}},
}