sets.exported={
    main={ name="Grioavolr", augments={'Blood Pact Dmg.+9','Pet: INT+9','Pet: Mag. Acc.+18',}},
    sub="Elan Strap",
    ammo="Sancus Sachet",
    head={ name="Apogee Crown", augments={'MP+60','Pet: "Mag.Atk.Bns."+30','Blood Pact Dmg.+7',}},
    body="Con. Doublet +1",
    hands={ name="Merlinic Dastanas", augments={'Pet: Attack+25 Pet: Rng.Atk.+25','Blood Pact Dmg.+8','Pet: INT+10','Pet: Mag. Acc.+8','Pet: "Mag.Atk.Bns."+1',}},
    legs={ name="Enticer's Pants", augments={'MP+50','Pet: Accuracy+15 Pet: Rng. Acc.+15','Pet: Mag. Acc.+15','Pet: Damage taken -5%',}},
    feet={ name="Apogee Pumps", augments={'MP+60','Pet: Attack+30','Blood Pact Dmg.+7',}},
    neck="Adad Amulet",
    waist="Incarnation Sash",
    left_ear="Enmerkar Earring",
    right_ear="Lugalbanda Earring",
    left_ring="Varar Ring",
    right_ring="Stikini Ring",
    back="Campestres's Cape",
}