sets.exported={
    main="Ragnarok",
    sub="Utu Grip",
    ammo="Staunch Tathlum",
    head="Sulevia's Mask +2",
    body="Sulevia's Plate. +2",
    hands="Sulev. Gauntlets +2",
    legs="Sulev. Cuisses +2",
    feet="Pumm. Calligae +3",
    neck="Loricate Torque +1",
    waist="Engraved Belt",
    left_ear="Eabani Earring",
    right_ear="Flashward Earring",
    left_ring="Archon Ring",
    right_ring="Defending Ring",
    back="Shadow Mantle",
}