sets.exported={
    main="Freydis",
    sub="Adapa Shield",
    ammo="Staunch Tathlum",
    head={ name="Valorous Mask", augments={'Mag. Acc.+22','MND+8','Chance of successful block +10','Accuracy+13 Attack+13','Mag. Acc.+12 "Mag.Atk.Bns."+12',}},
    body="Sulevia's Plate. +2",
    hands={ name="Agoge Mufflers +3", augments={'Enhances "Mighty Strikes" effect',}},
    legs="Arjuna Breeches",
    feet={ name="Souveran Schuhs", augments={'HP+80','Enmity+7','Potency of "Cure" effect received +10%',}},
    neck="Combatant's Torque",
    waist="Ioskeha Belt",
    left_ear="Thureous Earring",
    right_ear="Telos Earring",
    left_ring="Niqmaddu Ring",
    right_ring="Defending Ring",
    back={ name="Cichol's Mantle", augments={'STR+20','Accuracy+20 Attack+20','STR+10','"Dbl.Atk."+10',}},
}