sets.exported={
    main="Aeneas",
    sub={ name="Taming Sari", augments={'STR+10','DEX+10','DMG:+15','"Treasure Hunter"+1',}},
    range={ name="Linos", augments={'Accuracy+14','Sklchn.dmg.+4%','Quadruple Attack +2',}},
    head="Aya. Zucchetto +1",
    body="Ashera Harness",
    hands="Aya. Manopolas +1",
    legs="Jokushu Haidate",
    feet="Aya. Gambieras +1",
    neck="Caro Necklace",
    waist="Grunfeld Rope",
    left_ear="Ishvara Earring",
    right_ear={ name="Moonshade Earring", augments={'MP+25','TP Bonus +25',}},
    left_ring="Ilabrat Ring",
    right_ring="Hetairoi Ring",
    back={ name="Intarabus's Cape", augments={'DEX+20','Accuracy+20 Attack+20','"Dbl.Atk."+10',}},
}