sets.exported={
    main="Dojikiri Yasutsuna",
    sub="Utu Grip",
    ammo="Ginsen",
    head={ name="Valorous Mask", augments={'Accuracy+18 Attack+18','Weapon skill damage +3%','STR+9','Accuracy+1',}},
    body="Hiza. Haramaki +1",
    hands="Macabre Gaunt.",
    legs={ name="Valor. Hose", augments={'Accuracy+30','"Store TP"+8','CHR+7',}},
    feet="Danzo Sune-Ate",
    neck="Loricate Torque +1",
    waist="Flume Belt +1",
    left_ear="Cessance Earring",
    right_ear="Telos Earring",
    left_ring={ name="Dark Ring", augments={'Magic dmg. taken -3%','Phys. dmg. taken -6%',}},
    right_ring="Defending Ring",
    back="Solemnity Cape",
}