sets.exported={
    main={ name="Gridarvor", augments={'Pet: Accuracy+70','Pet: Attack+70','Pet: "Dbl. Atk."+15',}},
    sub="Elan Strap",
    ammo="Sancus Sachet",
    head={ name="Glyphic Horn +1", augments={'Enhances "Astral Flow" effect',}},
    body="Con. Doublet +1",
    hands="Lamassu Mitts +1",
    legs={ name="Enticer's Pants", augments={'MP+50','Pet: Accuracy+15 Pet: Rng. Acc.+15','Pet: Mag. Acc.+15','Pet: Damage taken -5%',}},
    feet={ name="Apogee Pumps", augments={'MP+60','Pet: Attack+30','Blood Pact Dmg.+7',}},
    neck="Incanter's Torque",
    waist="Incarnation Sash",
    left_ear="Enmerkar Earring",
    right_ear="Lugalbanda Earring",
    left_ring="Globidonta Ring",
    right_ring="Evoker's Ring",
    back={ name="Conveyance Cape", augments={'Summoning magic skill +1','Blood Pact Dmg.+2','Blood Pact ab. del. II -2',}},
}