sets.exported={
    main="Fettering Blade",
    sub="Nusku Shield",
    range="Molybdosis",
    ammo="Adlivun Bullet",
    head="Meganada Visor +1",
    body="Meg. Cuirie +1",
    hands="Meg. Gloves +1",
    legs="Meg. Chausses +1",
    feet="Meg. Jam. +1",
    neck="Iskur Gorget",
    waist="Yemaya Belt",
    left_ear="Infused Earring",
    right_ear="Neritic Earring",
    left_ring="Defending Ring",
    right_ring="Rajas Ring",
    back="Camulus's Mantle",
}