sets.exported={
    main="Fettering Blade",
    sub="Nusku Shield",
    range="Molybdosis",
    ammo="Adlivun Bullet",
    head="Meghanada Visor +2",
    body="Sayadio's Kaftan",
    hands="Meg. Gloves +2",
    legs="Meg. Chausses +2",
    feet="Meg. Jam. +2",
    neck="Iskur Gorget",
    waist="Yemaya Belt",
    left_ear="Infused Earring",
    right_ear="Neritic Earring",
    left_ring="Epona's Ring",
    right_ring="Ilabrat Ring",
    back={ name="Camulus's Mantle", augments={'AGI+20','Rng.Acc.+20 Rng.Atk.+20','"Store TP"+10',}},
}