	return {
		["Northern San d'Oria"] = {Option=1,Index=0},
		["Bastok Mines"] = {Option=1,Index=1},
		["Port Windurst"] = {Option=1,Index=2},
		["Ru\'Lude Gardens"] = {Option=1,Index=3},
		["Tavnazian Safehold"] = {Option=1,Index=4},
		["Aht Urhgan Whitegate"] = {Option=1,Index=5},
		["West Ronfaure"] = {Option=1,Index=6},
		["Fort Ghelsba"] = {Option=1,Index=7},
		["Bostaunieux Oubliette"] = {Option=1,Index=8},
		["King Ranperre's Tomb"] = {Option=1,Index=9},
		["La Theine Plateau"] = {Option=1,Index=10},
		["Valkurm Dunes"] = {Option=1,Index=11},
		["Konschtat Highlands"] = {Option=1,Index=12},
		["Ordelle\'s Caves"] = {Option=1,Index=13},
		["Gusgen Mines"] = {Option=1,Index=14},
		["Carpenters\' Landing"] = {Option=1,Index=15},
		["Jugner Forest"] = {Option=1,Index=16},
		["Batallia Downs"] = {Option=1,Index=17},
		["Davoi"] = {Option=1,Index=18},
		["The Eldieme Necropolis"] = {Option=1,Index=19},
		["North Gustaberg"] = {Option=1,Index=20},
		["Zeruhn Mines"] = {Option=1,Index=21},
		["Korroloka Tunnel"] = {Option=1,Index=22},
		["Dangruf Wadi"] = {Option=1,Index=23},
		["Passhow Marshlands"] = {Option=1,Index=24},
		["Rolanberry Fields"] = {Option=1,Index=25},
		["Beadeaux"] = {Option=1,Index=26},
		["Crawlers' Nest"] = {Option=1,Index=27},
		["West Sarutabaruta"] = {Option=1,Index=28},
		["Toraimarai Canal"] = {Option=1,Index=29},
		["Horutoto Ruins"] = {Option=1,Index=30},
		["Bibiki Bay"] = {Option=1,Index=31},
		["Tahrongi Canyon"] = {Option=1,Index=32},
		["Buburimu Peninsula"] = {Option=1,Index=33},
		["Maze of Shakhrami"] = {Option=1,Index=34},
		["Labyrinth of Onzozo"] = {Option=1,Index=35},
		["Meriphataud Mountains"] = {Option=1,Index=36},
		["Sauromugue Champaign"] = {Option=1,Index=37},
		["Castle Oztroja"] = {Option=1,Index=38},
		["Garlaige Citadel"] = {Option=1,Index=39},
		["Beaucedine Glacier"] = {Option=1,Index=40},
		["Ranguemont Pass"] = {Option=1,Index=41},
		["Xarcabard"] = {Option=1,Index=42},
		["Castle Zvahl Baileys"] = {Option=1,Index=43},
		["Qufim Island"] = {Option=1,Index=44},
		["Behemoth's Dominion"] = {Option=1,Index=45},
		["Lower Delkfutt\'s Tower"] = {Option=1,Index=46},
		["The Sanctuary of Zi\'Tah"] = {Option=1,Index=47},
		["Ro\'Maeve"] = {Option=1,Index=48},
		["Dragon\'s Aery"] = {Option=1,Index=49},
		["Eastern Altepa Desert"] = {Option=1,Index=50},
		["Western Altepa Desert"] = {Option=1,Index=51},
		["Rabao"] = {Option=1,Index=52},
		["Cape Teriggan"] = {Option=1,Index=53},
		["Valley of Sorrows"] = {Option=1,Index=54},
		["Kuftal Tunnel"] = {Option=1,Index=55},
		["Gustav Tunnel"] = {Option=1,Index=56},
		["Yuhtunga Jungle"] = {Option=1,Index=57},
		["Sea Serpent Grotto"] = {Option=1,Index=58},
		["Kazham"] = {Option=1,Index=59},
		["Norg"] = {Option=1,Index=60},
		["Yhoator Jungle"] = {Option=1,Index=61},
		["Temple of Uggalepih"] = {Option=1,Index=62},
		["Ifrit\'s Cauldron"] = {Option=1,Index=63},
		["Ru\'Aun Gardens"] = {Option=1,Index=64},
		["Oldton Movalpolos"] = {Option=1,Index=65},
		["Lufaise Meadows"] = {Option=1,Index=66},
		["Misareaux Coast"] = {Option=1,Index=67},
		["Phomiuna Aqueducts"] = {Option=1,Index=68},
		["Sacrarium"] = {Option=1,Index=69},
		["Wajaom Woodlands"] = {Option=1,Index=70},
		["Mamook"] = {Option=1,Index=71},
		["Aydeewa Subterrane"] = {Option=1,Index=72},
		["Halvung"] = {Option=1,Index=73},
		["Nashmau"] = {Option=1,Index=74},
		["Arrapago Reef"] = {Option=1,Index=75},
		["Caedarva Mire"] = {Option=1,Index=76},
		["Southern San d\'Oria \[S\]"] = {Option=1,Index=77},
		["East Ronfaure \[S\]"] = {Option=1,Index=78},
		["Jugner Forest \[S\]"] = {Option=1,Index=79},
		["Batallia Downs \[S\]"] = {Option=1,Index=80},
		["The Eldieme Necropolis \[S\]"] = {Option=1,Index=81},
		["Bastok Market \[S\]"] = {Option=1,Index=82},
		["North Gustaberg \[S\]"] = {Option=1,Index=83},
		["Grauberg \[S\]"] = {Option=1,Index=84},
		["Vunkerl Inlet \[S\]"] = {Option=1,Index=85},
		["Pashhow Marshlands \[S\]"] = {Option=1,Index=86},
		["Rolanberry Fields \[S\]"] = {Option=1,Index=87},
		["Crawlers\' Nest \[S\]"] = {Option=1,Index=88},
		["Windurst Waters \[S\]"] = {Option=1,Index=89},
		["West Sarutabaruta \[S\]"] = {Option=1,Index=90},
		["Fort Karugo-Narugo \[S\]"] = {Option=1,Index=91},
		["Meriphataud Mountains \[S\]"] = {Option=1,Index=92},
		["Sauromugue Champaign \[S\]"] = {Option=1,Index=93},
		["Garlaige Citadel \[S\]"] = {Option=1,Index=94},
		["Beaucedine Glacier \[S\]"] = {Option=1,Index=95},
		["Castle Zvahl Baileys \[S\]"] = {Option=1,Index=96},
		["Eastern Adoulin"] = {Option=1,Index=97},
	}
