	return {
		["Southern San d\'Oria 1"] = {Option=2,Index=0},
		["Southern San d\'Oria 2"] = {Option=2,Index=1},
		["Southern San d\'Oria 3"] = {Option=2,Index=2},
		["Northern San d\'Oria 1"] = {Option=2,Index=3},
		["Northern San d\'Oria 2"] = {Option=2,Index=4},
		["Northern San d\'Oria 3"] = {Option=2,Index=5},
		["Port San d\'Oria 1"] = {Option=2,Index=6},
		["Port San d\'Oria 2"] = {Option=2,Index=7},
		["Port San d\'Oria 3"] = {Option=2,Index=8},
		["Bastok Mines 1"] = {Option=2,Index=9},
		["Bastok Mines 2"] = {Option=2,Index=10},
		["Bastok Markets 1"] = {Option=2,Index=11},
		["Bastok Markets 2"] = {Option=2,Index=12},
		["Bastok Markets 3"] = {Option=2,Index=13},
		["Port Bastok 1"] = {Option=2,Index=14},
		["Port Bastok 2"] = {Option=2,Index=15},
		["Metalworks 1"] = {Option=2,Index=16},
		["Windurst Waters 1"] = {Option=2,Index=17},
		["Windurst Waters 2"] = {Option=2,Index=18},
		["Windurst Walls 1"] = {Option=2,Index=19},
		["Windurst Walls 2"] = {Option=2,Index=20},
		["Windurst Walls 3"] = {Option=2,Index=21},
		["Port Windurst 1"] = {Option=2,Index=22},
		["Port Windurst 2"] = {Option=2,Index=23},
		["Port Windurst 3"] = {Option=2,Index=24},
		["Windurst Woods 1"] = {Option=2,Index=25},
		["Windurst Woods 2"] = {Option=2,Index=26},
		["Windurst Woods 3"] = {Option=2,Index=27},
		["Windurst Woods 4"] = {Option=2,Index=28},
		["Ru\'Lude Gardens 1"] = {Option=2,Index=29},
		["Ru\'Lude Gardens 2"] = {Option=2,Index=30},
		["Ru\'Lude Gardens 3"] = {Option=2,Index=31},
		["Upper Jeuno 1"] = {Option=2,Index=32},
		["Upper Jeuno 2"] = {Option=2,Index=33},
		["Upper Jeuno 3"] = {Option=2,Index=34},
		["Lower Jeuno 1"] = {Option=2,Index=35},
		["Lower Jeuno 2"] = {Option=2,Index=36},
		["Port Jeuno 1"] = {Option=2,Index=37},
		["Port Jeuno 2"] = {Option=2,Index=38},
		["Kazham 1"] = {Option=2,Index=39},
		["Mhaura 1"] = {Option=2,Index=40},
		["Norg 1"] = {Option=2,Index=41},
		["Rabao 1"] = {Option=2,Index=42},
		["Selbina 1"] = {Option=2,Index=43},
		["Western Adoulin 1"] = {Option=2,Index=44},
		["Eastern Adoulin 1"] = {Option=2,Index=45},
		["Ceizak Battlegrounds 1"] = {Option=2,Index=46},
		["Foret de Hennetiel 1"] = {Option=2,Index=47},
		["Morimar Basalt Fields 1"] = {Option=2,Index=48},
		["Yorcia Weald 1"] = {Option=2,Index=49},
		["Marjami Ravine 1"] = {Option=2,Index=50},
		["Kamihr Drifts 1"] = {Option=2,Index=51},
		["Yughott Grotto 1"] = {Option=2,Index=52},
		["Palborough Mines 1"] = {Option=2,Index=53},
		["Giddeus 1"] = {Option=2,Index=54},
		["Fei\'Yin 1"] = {Option=2,Index=55},
		["Quicksand Caves 1"] = {Option=2,Index=56},
		["Den of Rancor 1"] = {Option=2,Index=57},
		["Castle Zvahl Keep 1"] = {Option=2,Index=58},
		["Ru\'Aun Gardens 1"] = {Option=2,Index=59},
		["Ru\'Aun Gardens 2"] = {Option=2,Index=60},
		["Ru\'Aun Gardens 3"] = {Option=2,Index=61},
		["Ru\'Aun Gardens 4"] = {Option=2,Index=62},
		["Ru\'Aun Gardens 5"] = {Option=2,Index=63},
		["Tavnazian Safehold 1"] = {Option=2,Index=64},
		["Aht Urhgan Whitegate 1"] = {Option=2,Index=65},
		["Nashmau 1"] = {Option=2,Index=66},
		["Al Zahbi 1"] = {Option=2,Index=67},
		["Southern San d\'Oria \[S\] 1"] = {Option=2,Index=68},
		["Bastok Markets \[S\] 1"] = {Option=2,Index=69},
		["Windurst Waters \[S\] 1"] = {Option=2,Index=70},
		["Upper Delkfutt\'s Tower 1"] = {Option=2,Index=71},
		["The Shrine of Ru\'Avitau 1"] = {Option=2,Index=72},
		["Riverne - Site \#B01 1"] = {Option=2,Index=73},
		["Bhaflau Thickets 1"] = {Option=2,Index=74},
		["Caedarva Mire 1"] = {Option=2,Index=75},
		["Uleguerand Range 1"] = {Option=2,Index=76},
		["Uleguerand Range 2"] = {Option=2,Index=77},
		["Uleguerand Range 3"] = {Option=2,Index=78},
		["Uleguerand Range 4"] = {Option=2,Index=79},
		["Uleguerand Range 5"] = {Option=2,Index=80},
		["Attohwa Chasm 1"] = {Option=2,Index=81},
		["Pso\'Xja 1"] = {Option=2,Index=82},
		["Newton Movalpolos 1"] = {Option=2,Index=83},
		["Riverne - Site #A01 1"] = {Option=2,Index=84},
		["Al\'Taieu 1"] = {Option=2,Index=85},
		["Al\'Taieu 2"] = {Option=2,Index=86},
		["Al\'Taieu 3"] = {Option=2,Index=87},
		["Grand Palace of Hu\'Xzoi 1"] = {Option=2,Index=88},
		["The Garden of Ru'Hmet 1"] = {Option=2,Index=89},
		["Mount Zhayolm 1"] = {Option=2,Index=90},
		["Cape Teriggan 1"] = {Option=2,Index=91},
		["The Boyahda Tree 1"] = {Option=2,Index=92},
		["Den of Rancor 2"] = {Option=2,Index=93},
		["Fei\'Yin 2"] = {Option=2,Index=94},
		["Ifrit\'s Cauldron 1"] = {Option=2,Index=95},
		["Quicksand Caves 2"] = {Option=2,Index=96},
		["Southern San d\'Oria 4"] = {Option=2,Index=97},
		["Northern San d\'Oria 4"] = {Option=2,Index=98},
		["Bastok Mines 3"] = {Option=2,Index=99},
		["Bastok Markets 4"] = {Option=2,Index=100},
		["Port Bastok 3"] = {Option=2,Index=101},
		["Metalworks 2"] = {Option=2,Index=102},
		["Windurst Waters 3"] = {Option=2,Index=103},
		["Norg 2"] = {Option=2,Index=104},
		["Rabao 2"] = {Option=2,Index=105},
		["Aht Urhgan Whitegate 2"] = {Option=2,Index=106},
		["Aht Urhgan Whitegate 3"] = {Option=2,Index=107},
		["Aht Urhgan Whitegate 4"] = {Option=2,Index=108},
		["Western Adoulin 2"] = {Option=2,Index=109},
		["Eastern Adoulin 2"] = {Option=2,Index=110},
		["Xarcabard \[S\] 1"] = {Option=2,Index=111},
		["Leafallia 1"] = {Option=2,Index=112},
		["Castle Zvahl Keep \[S\] 1"] = {Option=2,Index=113},
		["Qufim Island 1"] = {Option=2,Index=114},
		["Toraimarai Canal 1"] = {Option=2,Index=115},
		["Ra\'Kaznar Inner Court 1"] = {Option=2,Index=116},
		["Misareaux Coast 1"] = {Option=2,Index=117},
		["Windurst Waters 4"] = {Option=2,Index=118},
		["Windurst Woods 5"] = {Option=2,Index=119},
		["Tavnazian Safehold 2"] = {Option=2,Index=120},
		["Tavnazian Safehold 3"] = {Option=2,Index=121},
	}
